### ISSUE TITLE
You can use Felicity.example directly

### ISSUE THREAD

**Issue by WesTyler** [robertpallas/generator-hapi-plus#7]
The `entityFor` instances [here](https://github.com/robertpallas/generator-hapi-plus/blob/master/generators/test/index.js#L104-L106) are not necessary if you are just wanting to generate example data. :) You can call `.example` [directly with a schema](https://github.com/xogroup/felicity/blob/master/API.md#exampleschema-options):

```js
route.random[method][key] = Felicity.example(joiSchema);
```

There's certainly nothing wrong with `new`ing up an instance, just wanting to share info. Thanks for using Felicity! I'd love to hear any feedback you may have, even (especially!) if it's negative!

**Comment by robertpallas** [comment]
Thanks for Felicity @WesTyler . Using it here to generate data for automatic e2e tests on REST API endpoints but we have other usages for more complex stuff in private repos. No issues ATM.

**Comment by WesTyler** [comment]
Awesome! :D 
That's our primary use case too. Glad to hear it's not causing issues!

This generator is great, by the way. I've pointed several Hapi newbies in this direction!
